### ISSUE TITLE
Doesn't work on LTR

### ISSUE THREAD

**Issue by katagen** [Ludwig-K/QGisLinearReference#1]
I try it on 4 differents PC (3 Windows and one macOS), but I always have this error:
`AttributeError: type object 'Qgis' has no attribute 'WkbType' 
Traceback (most recent call last):
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\LinearReference.py", line 246, in set_map_tool_PolEvt
    self.mt_PolEvt = map_tools.PolEvt(self.iface)
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\PolEvt.py", line 504, in __init__
    self.check_settings()
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\PolEvt.py", line 3046, in check_settings
    data_layers = tools.MyToolFunctions.get_data_layers()
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\tools\MyToolFunctions.py", line 169, in get_data_layers
    qgis.core.Qgis.WkbType.NoGeometry
AttributeError: type object 'Qgis' has no attribute 'WkbType'
`

**Comment by Ludwig-K** [comment]
Hello, thanks for the message!

The reason is indeed that the enum Qgis::WkbType exists only since QGis version 3.30, but the currently available LTR is from version 3.28.8 'Firenze', where the same enum can be found under QgsWkbTypes.Type.
See https://api.qgis.org/api/classQgis.html#adf94495b88fbb3c5df092267ccc94509.

In a few days there will be a patched version that runs on the LTR version and has some new functionalities.

**Comment by Ludwig-K** [comment]
I just uploaded version 1.0.2, developed with LTR 3.28.8, but running on actual versions, too.
The new version must be approved and should be downloadable soon.
I Found and removed some other bugs, hopefully all.
Please test yourself and close this issue, if successful.
