### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by e-shirt** [Ludwig-K/QGisLinearReference#2]
I get the following Python error, but I am no programmer so I don't now how to handle it:

NameError: name 'apos' is not defined 
Traceback (most recent call last):
  File "C:\Users/%USER%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\LolEvt.py", line 3492, in s_insert_feature
    self.set_edit_pk(used_pk, False)
  File "C:\Users/%USER%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\LolEvt.py", line 1103, in set_edit_pk
    self.dlg_refresh_feature_selection_section()
  File "C:\Users/%USER%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LinearReferencing\map_tools\LolEvt.py", line 4408, in dlg_refresh_feature_selection_section
    data_label = data_label_plus = f"{apos}{data_evaled_exp}{apos}"
NameError: name 'apos' is not defined

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.0-Lima Lima, 311a8cb8a6 

The error occurs when inserting a LoL feature. Inserting does work though. I get this error on two different machines. I am using a OSM roads dataset with ~1000 objects as reference layer.

**Comment by Ludwig-K** [comment]
Oops...
Bug will be fixed in the next release, coming this week. 
Thanks for reporting!

**Comment by Ludwig-K** [comment]
I just uploaded version 1.0.2, I found and removed this bug (and some others, hopefully all...).
The new version must be approved and should be downloadable soon.
Please test yourself and close this issue, if successful.
